// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/download.dart';
import 'api/simple.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiSimpleInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => -665692884;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib_nebula',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<String> crateApiDownloadAddDownload({
    required String source,
    required String savePath,
  });

  Future<String> crateApiDownloadAddVideoDownload({
    required String url,
    required String savePath,
    String? formatId,
  });

  Future<void> crateApiDownloadCancelDownload({
    required String taskId,
    required bool deleteFiles,
  });

  Future<VideoInfo> crateApiDownloadGetVideoInfo({required String url});

  String crateApiSimpleGreet({required String name});

  Future<void> crateApiSimpleInitApp();

  Future<void> crateApiDownloadInitDownloadManager({
    required String downloadDir,
  });

  Future<bool> crateApiDownloadIsVideoUrl({required String url});

  Future<void> crateApiDownloadPauseDownload({required String taskId});

  Future<void> crateApiDownloadResumeDownload({required String taskId});

  Future<Stream<NebulaEvent>> crateApiDownloadSubscribeEvents();
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<String> crateApiDownloadAddDownload({
    required String source,
    required String savePath,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(source, serializer);
          sse_encode_String(savePath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiDownloadAddDownloadConstMeta,
        argValues: [source, savePath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDownloadAddDownloadConstMeta =>
      const TaskConstMeta(
        debugName: "add_download",
        argNames: ["source", "savePath"],
      );

  @override
  Future<String> crateApiDownloadAddVideoDownload({
    required String url,
    required String savePath,
    String? formatId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(url, serializer);
          sse_encode_String(savePath, serializer);
          sse_encode_opt_String(formatId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiDownloadAddVideoDownloadConstMeta,
        argValues: [url, savePath, formatId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDownloadAddVideoDownloadConstMeta =>
      const TaskConstMeta(
        debugName: "add_video_download",
        argNames: ["url", "savePath", "formatId"],
      );

  @override
  Future<void> crateApiDownloadCancelDownload({
    required String taskId,
    required bool deleteFiles,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(taskId, serializer);
          sse_encode_bool(deleteFiles, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiDownloadCancelDownloadConstMeta,
        argValues: [taskId, deleteFiles],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDownloadCancelDownloadConstMeta =>
      const TaskConstMeta(
        debugName: "cancel_download",
        argNames: ["taskId", "deleteFiles"],
      );

  @override
  Future<VideoInfo> crateApiDownloadGetVideoInfo({required String url}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(url, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_video_info,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiDownloadGetVideoInfoConstMeta,
        argValues: [url],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDownloadGetVideoInfoConstMeta =>
      const TaskConstMeta(debugName: "get_video_info", argNames: ["url"]);

  @override
  String crateApiSimpleGreet({required String name}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(name, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 5)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleGreetConstMeta,
        argValues: [name],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleGreetConstMeta =>
      const TaskConstMeta(debugName: "greet", argNames: ["name"]);

  @override
  Future<void> crateApiSimpleInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  Future<void> crateApiDownloadInitDownloadManager({
    required String downloadDir,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(downloadDir, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiDownloadInitDownloadManagerConstMeta,
        argValues: [downloadDir],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDownloadInitDownloadManagerConstMeta =>
      const TaskConstMeta(
        debugName: "init_download_manager",
        argNames: ["downloadDir"],
      );

  @override
  Future<bool> crateApiDownloadIsVideoUrl({required String url}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(url, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiDownloadIsVideoUrlConstMeta,
        argValues: [url],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDownloadIsVideoUrlConstMeta =>
      const TaskConstMeta(debugName: "is_video_url", argNames: ["url"]);

  @override
  Future<void> crateApiDownloadPauseDownload({required String taskId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(taskId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiDownloadPauseDownloadConstMeta,
        argValues: [taskId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDownloadPauseDownloadConstMeta =>
      const TaskConstMeta(debugName: "pause_download", argNames: ["taskId"]);

  @override
  Future<void> crateApiDownloadResumeDownload({required String taskId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(taskId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiDownloadResumeDownloadConstMeta,
        argValues: [taskId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDownloadResumeDownloadConstMeta =>
      const TaskConstMeta(debugName: "resume_download", argNames: ["taskId"]);

  @override
  Future<Stream<NebulaEvent>> crateApiDownloadSubscribeEvents() async {
    final sink = RustStreamSink<NebulaEvent>();
    await handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_StreamSink_nebula_event_Sse(sink, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiDownloadSubscribeEventsConstMeta,
        argValues: [sink],
        apiImpl: this,
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiDownloadSubscribeEventsConstMeta =>
      const TaskConstMeta(debugName: "subscribe_events", argNames: ["sink"]);

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  RustStreamSink<NebulaEvent> dco_decode_StreamSink_nebula_event_Sse(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  ProgressEvent dco_decode_box_autoadd_progress_event(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_progress_event(raw);
  }

  @protected
  BigInt dco_decode_box_autoadd_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_u_64(raw);
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<VideoFormat> dco_decode_list_video_format(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_video_format).toList();
  }

  @protected
  NebulaEvent dco_decode_nebula_event(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return NebulaEvent_TaskAdded(
          taskId: dco_decode_String(raw[1]),
          name: dco_decode_String(raw[2]),
        );
      case 1:
        return NebulaEvent_TaskStarted(taskId: dco_decode_String(raw[1]));
      case 2:
        return NebulaEvent_ProgressUpdated(
          taskId: dco_decode_String(raw[1]),
          progress: dco_decode_box_autoadd_progress_event(raw[2]),
        );
      case 3:
        return NebulaEvent_TaskCompleted(taskId: dco_decode_String(raw[1]));
      case 4:
        return NebulaEvent_TaskFailed(
          taskId: dco_decode_String(raw[1]),
          error: dco_decode_String(raw[2]),
        );
      case 5:
        return NebulaEvent_TaskPaused(taskId: dco_decode_String(raw[1]));
      case 6:
        return NebulaEvent_TaskResumed(taskId: dco_decode_String(raw[1]));
      case 7:
        return NebulaEvent_TaskRemoved(taskId: dco_decode_String(raw[1]));
      case 8:
        return NebulaEvent_MetadataReceived(
          taskId: dco_decode_String(raw[1]),
          name: dco_decode_String(raw[2]),
          totalSize: dco_decode_u_64(raw[3]),
          fileCount: dco_decode_usize(raw[4]),
        );
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  BigInt? dco_decode_opt_box_autoadd_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_64(raw);
  }

  @protected
  ProgressEvent dco_decode_progress_event(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return ProgressEvent(
      taskId: dco_decode_String(arr[0]),
      totalSize: dco_decode_u_64(arr[1]),
      downloadedSize: dco_decode_u_64(arr[2]),
      downloadSpeed: dco_decode_u_64(arr[3]),
      percentage: dco_decode_f_64(arr[4]),
      etaSecs: dco_decode_opt_box_autoadd_u_64(arr[5]),
    );
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  VideoFormat dco_decode_video_format(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return VideoFormat(
      formatId: dco_decode_String(arr[0]),
      ext: dco_decode_String(arr[1]),
      resolution: dco_decode_opt_String(arr[2]),
      filesize: dco_decode_opt_box_autoadd_u_64(arr[3]),
      formatNote: dco_decode_opt_String(arr[4]),
    );
  }

  @protected
  VideoInfo dco_decode_video_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return VideoInfo(
      id: dco_decode_String(arr[0]),
      title: dco_decode_String(arr[1]),
      thumbnail: dco_decode_opt_String(arr[2]),
      duration: dco_decode_opt_box_autoadd_u_64(arr[3]),
      uploader: dco_decode_opt_String(arr[4]),
      formats: dco_decode_list_video_format(arr[5]),
    );
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  RustStreamSink<NebulaEvent> sse_decode_StreamSink_nebula_event_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  ProgressEvent sse_decode_box_autoadd_progress_event(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_progress_event(deserializer));
  }

  @protected
  BigInt sse_decode_box_autoadd_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_64(deserializer));
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<VideoFormat> sse_decode_list_video_format(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <VideoFormat>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_video_format(deserializer));
    }
    return ans_;
  }

  @protected
  NebulaEvent sse_decode_nebula_event(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        var var_taskId = sse_decode_String(deserializer);
        var var_name = sse_decode_String(deserializer);
        return NebulaEvent_TaskAdded(taskId: var_taskId, name: var_name);
      case 1:
        var var_taskId = sse_decode_String(deserializer);
        return NebulaEvent_TaskStarted(taskId: var_taskId);
      case 2:
        var var_taskId = sse_decode_String(deserializer);
        var var_progress = sse_decode_box_autoadd_progress_event(deserializer);
        return NebulaEvent_ProgressUpdated(
          taskId: var_taskId,
          progress: var_progress,
        );
      case 3:
        var var_taskId = sse_decode_String(deserializer);
        return NebulaEvent_TaskCompleted(taskId: var_taskId);
      case 4:
        var var_taskId = sse_decode_String(deserializer);
        var var_error = sse_decode_String(deserializer);
        return NebulaEvent_TaskFailed(taskId: var_taskId, error: var_error);
      case 5:
        var var_taskId = sse_decode_String(deserializer);
        return NebulaEvent_TaskPaused(taskId: var_taskId);
      case 6:
        var var_taskId = sse_decode_String(deserializer);
        return NebulaEvent_TaskResumed(taskId: var_taskId);
      case 7:
        var var_taskId = sse_decode_String(deserializer);
        return NebulaEvent_TaskRemoved(taskId: var_taskId);
      case 8:
        var var_taskId = sse_decode_String(deserializer);
        var var_name = sse_decode_String(deserializer);
        var var_totalSize = sse_decode_u_64(deserializer);
        var var_fileCount = sse_decode_usize(deserializer);
        return NebulaEvent_MetadataReceived(
          taskId: var_taskId,
          name: var_name,
          totalSize: var_totalSize,
          fileCount: var_fileCount,
        );
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  BigInt? sse_decode_opt_box_autoadd_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  ProgressEvent sse_decode_progress_event(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_taskId = sse_decode_String(deserializer);
    var var_totalSize = sse_decode_u_64(deserializer);
    var var_downloadedSize = sse_decode_u_64(deserializer);
    var var_downloadSpeed = sse_decode_u_64(deserializer);
    var var_percentage = sse_decode_f_64(deserializer);
    var var_etaSecs = sse_decode_opt_box_autoadd_u_64(deserializer);
    return ProgressEvent(
      taskId: var_taskId,
      totalSize: var_totalSize,
      downloadedSize: var_downloadedSize,
      downloadSpeed: var_downloadSpeed,
      percentage: var_percentage,
      etaSecs: var_etaSecs,
    );
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  VideoFormat sse_decode_video_format(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_formatId = sse_decode_String(deserializer);
    var var_ext = sse_decode_String(deserializer);
    var var_resolution = sse_decode_opt_String(deserializer);
    var var_filesize = sse_decode_opt_box_autoadd_u_64(deserializer);
    var var_formatNote = sse_decode_opt_String(deserializer);
    return VideoFormat(
      formatId: var_formatId,
      ext: var_ext,
      resolution: var_resolution,
      filesize: var_filesize,
      formatNote: var_formatNote,
    );
  }

  @protected
  VideoInfo sse_decode_video_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_title = sse_decode_String(deserializer);
    var var_thumbnail = sse_decode_opt_String(deserializer);
    var var_duration = sse_decode_opt_box_autoadd_u_64(deserializer);
    var var_uploader = sse_decode_opt_String(deserializer);
    var var_formats = sse_decode_list_video_format(deserializer);
    return VideoInfo(
      id: var_id,
      title: var_title,
      thumbnail: var_thumbnail,
      duration: var_duration,
      uploader: var_uploader,
      formats: var_formats,
    );
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_StreamSink_nebula_event_Sse(
    RustStreamSink<NebulaEvent> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_nebula_event,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_progress_event(
    ProgressEvent self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_progress_event(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self, serializer);
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_video_format(
    List<VideoFormat> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_video_format(item, serializer);
    }
  }

  @protected
  void sse_encode_nebula_event(NebulaEvent self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case NebulaEvent_TaskAdded(taskId: final taskId, name: final name):
        sse_encode_i_32(0, serializer);
        sse_encode_String(taskId, serializer);
        sse_encode_String(name, serializer);
      case NebulaEvent_TaskStarted(taskId: final taskId):
        sse_encode_i_32(1, serializer);
        sse_encode_String(taskId, serializer);
      case NebulaEvent_ProgressUpdated(
        taskId: final taskId,
        progress: final progress,
      ):
        sse_encode_i_32(2, serializer);
        sse_encode_String(taskId, serializer);
        sse_encode_box_autoadd_progress_event(progress, serializer);
      case NebulaEvent_TaskCompleted(taskId: final taskId):
        sse_encode_i_32(3, serializer);
        sse_encode_String(taskId, serializer);
      case NebulaEvent_TaskFailed(taskId: final taskId, error: final error):
        sse_encode_i_32(4, serializer);
        sse_encode_String(taskId, serializer);
        sse_encode_String(error, serializer);
      case NebulaEvent_TaskPaused(taskId: final taskId):
        sse_encode_i_32(5, serializer);
        sse_encode_String(taskId, serializer);
      case NebulaEvent_TaskResumed(taskId: final taskId):
        sse_encode_i_32(6, serializer);
        sse_encode_String(taskId, serializer);
      case NebulaEvent_TaskRemoved(taskId: final taskId):
        sse_encode_i_32(7, serializer);
        sse_encode_String(taskId, serializer);
      case NebulaEvent_MetadataReceived(
        taskId: final taskId,
        name: final name,
        totalSize: final totalSize,
        fileCount: final fileCount,
      ):
        sse_encode_i_32(8, serializer);
        sse_encode_String(taskId, serializer);
        sse_encode_String(name, serializer);
        sse_encode_u_64(totalSize, serializer);
        sse_encode_usize(fileCount, serializer);
    }
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_64(BigInt? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_64(self, serializer);
    }
  }

  @protected
  void sse_encode_progress_event(ProgressEvent self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.taskId, serializer);
    sse_encode_u_64(self.totalSize, serializer);
    sse_encode_u_64(self.downloadedSize, serializer);
    sse_encode_u_64(self.downloadSpeed, serializer);
    sse_encode_f_64(self.percentage, serializer);
    sse_encode_opt_box_autoadd_u_64(self.etaSecs, serializer);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_video_format(VideoFormat self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.formatId, serializer);
    sse_encode_String(self.ext, serializer);
    sse_encode_opt_String(self.resolution, serializer);
    sse_encode_opt_box_autoadd_u_64(self.filesize, serializer);
    sse_encode_opt_String(self.formatNote, serializer);
  }

  @protected
  void sse_encode_video_info(VideoInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.title, serializer);
    sse_encode_opt_String(self.thumbnail, serializer);
    sse_encode_opt_box_autoadd_u_64(self.duration, serializer);
    sse_encode_opt_String(self.uploader, serializer);
    sse_encode_list_video_format(self.formats, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}
